// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDPYBOPnmFc62fjsgjpSu4T21gNwcYjo',
    appId: '1:832147030033:web:a02cd2c4ea3f95b3a671b0',
    messagingSenderId: '832147030033',
    projectId: 'flutter-firebase-a4bf1',
    authDomain: 'flutter-firebase-a4bf1.firebaseapp.com',
    storageBucket: 'flutter-firebase-a4bf1.firebasestorage.app',
    measurementId: 'G-F64TZPCPL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbENCtoFcK0vF_aOBvxOXD1yzIvnPQZek',
    appId: '1:832147030033:android:2585d67427d963aea671b0',
    messagingSenderId: '832147030033',
    projectId: 'flutter-firebase-a4bf1',
    storageBucket: 'flutter-firebase-a4bf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3XccCW6_z_zcoD9Z-QsM0n1ZP6aaeXQ',
    appId: '1:832147030033:ios:a07cacb0e8edc75ba671b0',
    messagingSenderId: '832147030033',
    projectId: 'flutter-firebase-a4bf1',
    storageBucket: 'flutter-firebase-a4bf1.firebasestorage.app',
    iosBundleId: 'com.example.learnfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs3XccCW6_z_zcoD9Z-QsM0n1ZP6aaeXQ',
    appId: '1:832147030033:ios:a07cacb0e8edc75ba671b0',
    messagingSenderId: '832147030033',
    projectId: 'flutter-firebase-a4bf1',
    storageBucket: 'flutter-firebase-a4bf1.firebasestorage.app',
    iosBundleId: 'com.example.learnfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbDPYBOPnmFc62fjsgjpSu4T21gNwcYjo',
    appId: '1:832147030033:web:5aed1c06c2c2c9e3a671b0',
    messagingSenderId: '832147030033',
    projectId: 'flutter-firebase-a4bf1',
    authDomain: 'flutter-firebase-a4bf1.firebaseapp.com',
    storageBucket: 'flutter-firebase-a4bf1.firebasestorage.app',
    measurementId: 'G-SLJMR29JWB',
  );

}